version: '3.9'

services:
  app:
    container_name: ticketAppBff
    build: .
    # command: ./scripts/run.sh
    ports:
      - '${APP_PORT:-8082}:8082'
      - '9230:9230' # Debug port
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
    env_file:
      - .env.docker
